[phases.build]
commands = [
  "cd backend && npm install",
  "cd frontend && npm install && npm run build"
]

[phases.start]
commands = [
  "cd backend && npm start"
]

[static]
directory = "frontend/dist"